apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-frontend
  namespace: survey-app
spec:
  replicas: 3                         # optional: match what Jenkins scales to
  selector:
    matchLabels:
      app: survey-frontend
  template:
    metadata:
      labels:
        app: survey-frontend
    spec:
      containers:
        - name: survey-frontend
          image: dgarapati03/survey-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000     
          env:
            - name: VITE_API_BASE
              value: "http://survey-backend.survey-app.svc.cluster.local:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: survey-frontend
  namespace: survey-app
spec:
  selector:
    app: survey-frontend
  ports:
    - port: 80
      targetPort: 8000               
  type: LoadBalancer
